
import numpy as np
import paddle
import paddle.incubate.nn.functional as F
import TokenDispatcherUtils as TDU

def compare_tensors(a, b):
    # 形状一致性检查
    assert a.shape == b.shape, "输入张量形状不一致"
    
    # 计算绝对差距
    abs_diff = np.abs(a - b)
    max_abs_val = np.max(abs_diff)
    max_abs_flat_idx = np.argmax(abs_diff)
    max_abs_idx = np.unravel_index(max_abs_flat_idx, a.shape)
    
    # 计算相对差距（防止除以零）
    denominator = np.maximum(np.abs(a), np.abs(b))
    rel_diff = np.divide(
        abs_diff, 
        denominator, 
        out=np.zeros_like(abs_diff),
        where=(denominator != 0)
    )
    max_rel_val = np.max(rel_diff)
    max_rel_flat_idx = np.argmax(rel_diff)
    max_rel_idx = np.unravel_index(max_rel_flat_idx, a.shape)
    

    # 打印结果
    print("\n[最大绝对差距]" f"位置: {max_abs_idx}")
    print(f"a[{max_abs_idx}] = {a[max_abs_idx]:.6g}" + f"\t b[{max_abs_idx}] = {b[max_abs_idx]:.6g}" + f"\t 绝对差值: {max_abs_val:.6g}\n")
    
    print("[最大相对差距]" f"位置: {max_rel_idx}")
    print(f"a[{max_rel_idx}] = {a[max_rel_idx]:.6g}" + f"\t b[{max_rel_idx}] = {b[max_rel_idx]:.6g}" + f"\t 相对差值: {max_rel_val:.6g}\n")
    print("周围元素比较-a:")
    print(f"{a[max_rel_idx[0], (max_rel_idx[1] - 10):(max_rel_idx[1] + 10)]} ")
    print("周围元素比较-b:")
    print(f"{b[max_rel_idx[0], (max_rel_idx[1] - 10):(max_rel_idx[1] + 10)]} ")
    
    # 返回结构化结果
    return {
        'max_absolute': {
            'index': max_abs_idx,
            'a_value': a[max_abs_idx],
            'b_value': b[max_abs_idx],
            'difference': max_abs_val
        },
        'max_relative': {
            'index': max_rel_idx,
            'a_value': a[max_rel_idx],
            'b_value': b[max_rel_idx],
            'difference': max_rel_val
        }
    }

def verify_regroup_token():
    expert_num = 3
    seqlen = 5 
    h1 = 8
    h2 = 4
    tokens = [ 
        [1,1,1,1,1,1,1,1],
        [3,3,3,3,3,3,3,3],
        [2,2,2,2,2,2,2,2],
        [5,5,5,5,5,5,5,5],
        [4,4,4,4,4,4,4,4],
    ]
    dout = [
        [0.1,0.1,0.1,0.1],
        [0.3,0.3,0.3,0.3],
        [0.2,0.2,0.2,0.2],
        [0.5,0.5,0.5,0.5],
        [0.4,0.4,0.4,0.4],
    ]
    expert_idx = [0,1,0,2,1]
    token_per_experts = [2,2,1]
    expected_tokens= [
        [1,1,1,1,1,1,1,1],
        [2,2,2,2,2,2,2,2],
        [3,3,3,3,3,3,3,3],
        [4,4,4,4,4,4,4,4],
        [5,5,5,5,5,5,5,5],
        [0,0,0,0,0,0,0,0]
    ]
    expected_dout = [
        [0.1,0.1,0.1,0.1],
        [0.2,0.2,0.2,0.2],
        [0.3,0.3,0.3,0.3],
        [0.4,0.4,0.4,0.4],
        [0.5,0.5,0.5,0.5],
        [0.,0.,0.,0.]
    ]

    tokens =  paddle.to_tensor(tokens, dtype="bfloat16")
    dout =  paddle.to_tensor(dout, dtype="bfloat16")
    expert_idx = paddle.to_tensor(expert_idx,dtype="int32")
    expected_tokens = paddle.to_tensor(expected_tokens, dtype="bfloat16")
    expected_dout = paddle.to_tensor(expected_dout, dtype="bfloat16")
    result_tokens, result_dout= TDU.regroup_tokens(
        tokens,
        dout,
        expert_idx,
        expert_num=expert_num,
        token_max_per_expert=2)
    print("##### executed unpadded")

    print("-------- result_padded Generated by fused op: ------------")
    print(result_tokens)
    print("-------- result_padded expected : ------------")
    print(expected_tokens)
    print("-------- dout_padded Generated by fused op: ------------")
    print(result_dout)
    print("-------- dout_padded expected : ------------")
    print(expected_dout)
    
def run():
    verify_regroup_token()

if __name__ == "__main__":
    run()