name: "tokenizer"
backend: "python"
max_batch_size: 64

input [
  {
    name: "INPUT_0"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "OUTPUT_0"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "OUTPUT_1"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]

instance_group [
  {
      count: 1
      kind: KIND_CPU
  }
]
