codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default: 
      target: 75% # overall project Coverage < 75%  CI will fail
      informational: true
    patch:
      default: 
      target: 90% # lines adjusted  Coverage < 90%  CI will fail
      informational: true
