# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
  include: all
  recursive: true

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
#formats:
#   - pdf

# # custome building process,
# # get more details: https://docs.readthedocs.io/en/stable/build-customization.html
# build:
#   os: "ubuntu-20.04"
#   languages:
#     python: "3.9"
#   jobs:
#     pre_install:
#       # fix the installation issue: 
#       # get more details: https://github.com/PaddlePaddle/Paddle/issues/45146
#       - apt install libgomp1

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    - method: setuptools
      path: .
  system_packages: true