_base_: ./pretrain_gpt_base.yaml

Global:
  global_batch_size: 
  local_batch_size: 1
  micro_batch_size: 1


Model:
  vocab_size: 50304
  hidden_size: 1024
  num_layers: 4
  num_attention_heads: 16
  ffn_hidden_size: 4096
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: False
  fuse_attn_qkv: True
  sequence_parallel: False # TODO make sequence_parallel as an independent parallel and be set id Distributed


Distributed:
  dp_degree: 1
  mp_degree: 8
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
