_base_: ./pretrain_gpt_base.yaml

Global:
  global_batch_size: 1
  local_batch_size: 1
  micro_batch_size: 1


Model:
  vocab_size: 50304
  hidden_size: 12288
  num_layers: 4
  num_attention_heads: 96
  ffn_hidden_size: 49152
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: True
  recompute_granularity: 'core_attn'
  no_recompute_layers:
  sequence_parallel: True
  fused_linear: True
  

Distributed:
  dp_degree: 1
  mp_degree: 1
  pp_degree: 2
  sharding:
    sharding_degree: 1
    sharding_stage: 1
