_base_: ./pretrain_gpt_base.yaml

Global:
  global_batch_size: 
  local_batch_size: 1536
  micro_batch_size: 1


Model:
  vocab_size: 51200
  hidden_size: 12288
  num_layers: 96
  num_attention_heads: 96
  ffn_hidden_size:
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: True
  recompute_granularity: 'core_attn'
  no_recompute_layers:
  virtual_pp_degree: 1
  sequence_parallel: True
  fused_linear: True
  

Distributed:
  dp_degree:
  mp_degree: 8
  pp_degree: 16
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
    reduce_overlap: False
    broadcast_overlap: False
