_base_: ./pretrain_gpt_base.yaml

Global:
  global_batch_size: 
  local_batch_size: 2
  micro_batch_size: 1


Model:
  vocab_size: 50304
  hidden_size: 2048
  num_layers: 24
  num_attention_heads: 16
  ffn_hidden_size: 8192
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: True
  recompute_granularity:
  no_recompute_layers:
  use_flash_attn: True
  sequence_parallel: False
  

Distributed:
  dp_degree: 1
  mp_degree: 1
  pp_degree: 1
  sep_degree: 8
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
    reduce_overlap: False
    broadcast_overlap: False
