_base_: ./pretrain_gpt_base.yaml


Engine:
  mix_precision:
    enable: True
    dtype: "float16"
    level: "o2"
    scale_loss: 32768.0
    custom_black_list: ["reduce_sum", "c_softmax_with_cross_entropy", "elementwise_div", "where"]
    custom_white_list: ["lookup_table", "lookup_table_v2"]
    use_fp16_guard: False


Generation:
  top_k: 1
  top_p: 0.9
  temperature: 1.0
  min_dec_len: 1
  max_dec_len: 8
  use_topp_sampling: True
  num_return_sequences: 1
  decode_strategy: "sampling"
  use_topp_sampling: True
  early_finish: True


Model:
  module: GPTGenerationModuleAuto
  vocab_size: 50432
  hidden_size: 5120
  num_layers: 40
  num_attention_heads: 40
  ffn_hidden_size: 
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 4096
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: True
  recompute_granularity: 'full'
  no_recompute_layers:


Distributed:
  dp_degree: 1
  mp_degree: 8
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
