cross-lingual-transfer:
  model_name_or_path: __internal_testing__/ernie-m
  task_type: cross-lingual-transfer
  max_seq_length: 256
  per_device_train_batch_size: 16 
  learning_rate: 5e-5
  classifier_dropout: 0.1
  weight_decay: 0.0
  layerwise_decay: 0.8
  max_steps: 2
  logging_steps: 1
  save_steps: 2
  output_dir: ./tmp/
  device: gpu
  fp16: False

translate-train-all:
  model_name_or_path: __internal_testing__/ernie-m
  task_type: translate-train-all
  max_seq_length: 256
  per_device_train_batch_size: 16 
  learning_rate: 5e-5
  classifier_dropout: 0.1
  weight_decay: 0.0
  layerwise_decay: 0.8
  max_steps: 2
  logging_steps: 1
  save_steps: 2
  output_dir: ./tmp/
  device: gpu
  fp16: False