edim: 150
lindim: 75
nhop: 7
mem_size: 200
batch_size: 128
nepoch: 100
init_lr: 0.01
init_hid: 0.1
init_std: 0.05
max_grad_norm: 50
data_dir: "data/ptb"
checkpoint_dir: "checkpoints"
model_name: "model"
recover_train: False
data_name: "ptb"
show: True
srand: 17814
log_epoch: 5
target_ppl: 147
