version: '1.1.0'

components:
  - name: PreProcessor
    params:
          max_examples: -1
    type: SentaProcessor
  - name: Senta
    params:
          model: uie-senta-base
          schema: [{'评价维度': ['观点词', '情感倾向[正向,负向,未提及]']}]
          task: sentiment_analysis
          aspects:
          max_seq_len: 512
          batch_size: 4
          split_sentence: False
          position_prob: 0.5
          lazy_load: False
          num_workers: 0
          use_fast: False
    type: UIESenta
  - name: Visualization
    params:
          font_name: SimHei
    type: SentaVisualization

pipelines:
  - name: senta_pipeline
    nodes:
      - name: PreProcessor
        inputs: [File]
      - name: Senta
        inputs: [PreProcessor]
      - name: Visualization
        inputs: [Senta]
