model_name_or_path: gpt2-medium-en
task_name: SST-2
max_seq_length: 128
per_device_train_batch_size: 32  
learning_rate: 2e-5
num_train_epochs: 3
logging_steps: 1
save_steps: 500
output_dir: ./output_dir/glue
eval_steps: 1
device: gpu
do_train: true