model_name_or_path: gpt2-en
input_dir: ./data
output_dir: ./output_dir/pretrain
weight_decay: 0.01
max_steps: 500000
save_steps: 100000
device: gpu
lr_decay_style: none
warmup_steps: 320000
warmup_ratio: 0.01
per_device_train_batch_size: 4
eval_steps: 100
do_train: true
do_predict: true