edim: 500
lindim: 250
nhop: 7
mem_size: 100
batch_size: 128
nepoch: 100
init_lr: 0.01
init_hid: 0.1
init_std: 0.05
max_grad_norm: 50
data_dir: "data/text8"
checkpoint_dir: "models"
model_name: "model_text8"
recover_train: False
data_name: "text8"
show: True
log_epoch: 5
target_ppl: 147
