model_type: gpt
model_name_or_path: gpt2-en
input_dir: ./data
output_dir: output
weight_decay: 0.01
grad_clip: 1.0
max_steps: 500000
save_steps: 100000
decay_steps: 320000
warmup_rate: 0.01
micro_batch_size: 4
device: gpu