msra_ner:
  model_name_or_path: __internal_testing__/gpt_cn
  max_seq_length: 32
  per_device_eval_batch_size: 4
  learning_rate: 2e-5
  num_train_epochs: 3
  logging_steps: 25
  save_steps: 250
  output_dir: ./output_dir/msra_ner/
  device: cpu
  do_train: true
  max_steps: 10
  

glue:
  model_name_or_path: __internal_testing__/gpt
  task_name: SST-2
  # task_name: mnli
  max_seq_length: 128
  per_device_train_batch_size: 32  
  learning_rate: 2e-5
  num_train_epochs: 3
  logging_steps: 1
  save_steps: 500
  output_dir: ./output_dir/glue
  max_steps: 10
  eval_steps: 1
  device: cpu
  do_train: true

pretrain:
  model_name_or_path: __internal_testing__/gpt
  input_dir: ./data
  output_dir: ./output_dir/pretrain
  weight_decay: 0.01
  max_steps: 50
  lr_decay_style: none
  save_steps: 10
  warmup_steps: 320000
  warmup_ratio: 0.01
  per_device_train_batch_size: 4
  device: cpu
  eval_steps: 100
  do_train: true
  do_predict: true