name: Build PR CI-Docker

on:
  push:
    branches:
      - develop
    paths:
      - "requirements*"
      - "scripts/regression/requirements_ci.txt"
      - "tests/requirements.txt"
      - "setup.py"
      - ".github/workflows/build-ci-docker-images.yml"
  pull_request:
    paths:
      - "requirements*"
      - "scripts/regression/requirements_ci.txt"
      - "tests/requirements.txt"
      - "setup.py"
      - ".github/workflows/build-ci-docker-images.yml"
  schedule:
    - cron: "5 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  work_dir: /workspace/PaddleNLP
  PaddleNLP_ROOT: /workspace/PaddleNLP
  TASK: PaddleNLP-CI-${{ github.event.pull_request.number }}-build-docker
  BRANCH: ${{ github.event.pull_request.base.ref }}
  CI_name: build-docker
  no_proxy: "localhost,bj.bcebos.com,su.bcebos.com,bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"

jobs:
  build-paddlenlp-ci-docker:
    name: build-paddlenlp-ci-docker
    runs-on: [self-hosted, 4gpu]
    steps:
      - name: Download Code
        env:
          work_dir: ${{ github.workspace }}
        run: |
          sudo rm -rf * .[^.]*
          echo "Downloading PaddleNLP.tar.gz"
          wget -q --no-proxy  https://paddle-qa.bj.bcebos.com/CodeSync/develop/PaddleNLP.tar --no-check-certificate
          echo "Extracting PaddleNLP.tar.gz"
          tar xf PaddleNLP.tar && rm -rf PaddleNLP.tar
          source ${{ github.workspace }}/../../../proxy
          cd PaddleNLP
          git config --global user.name "PaddleCI"
          git config --global user.email "paddle_ci@example.com"
          git pull
          git submodule update --init --recursive --force
          git fetch origin pull/${PR_ID}/head
          git checkout -b PR_${PR_ID} FETCH_HEAD
          git remote add upstream https://github.com/PaddlePaddle/PaddleNLP.git
          git fetch upstream ${BRANCH}
          git merge ${BRANCH}
          git diff --numstat ${BRANCH} |awk '{print $NF}'
          git log --pretty=oneline -10
      - name: Write Dockerfile Inline
        env:
          work_dir: ${{ github.workspace }}/PaddleNLP
        run: |
          cat <<EOF > Dockerfile
          FROM iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu18.04-gcc8.2-cuda11.8-cudnn8.6-nccl2.15.5-libsndfile
          RUN unlink /usr/bin/python3 && ln -sf python3.10 /usr/bin/python3
          RUN python -m pip config --user set global.index http://pip.baidu-int.com/search/
          RUN python -m pip config --user set global.index-url http://pip.baidu-int.com/simple
          RUN python -m pip config --user set global.trusted-host pip.baidu-int.com
          RUN python -m pip install bce-python-sdk==0.8.74
          RUN python -m pip install --no-cache-dir https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuSome-LinuxCentos-Gcc82-Cuda118-Cudnn86-Trt85-Py310-CINN-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl
          COPY PaddleNLP/ /tmp/paddlenlp/
          WORKDIR /tmp/paddlenlp
          RUN python -m pip install -r requirements.txt
          RUN python -m pip install -r requirements-dev.txt
          RUN python -m pip install -r scripts/regression/requirements_ci.txt
          RUN python -m pip install -r tests/requirements.txt
          RUN python setup.py bdist_wheel > /dev/null
          RUN python -m pip install dist/*.whl
          WORKDIR /
          RUN rm -rf /tmp/paddlenlp
          CMD ["python3"]
          EOF
      
      - name: Build Docker Image
        run: |
          docker build -t iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu18.04-gcc8.2-cuda11.8-cudnn8.6-nccl2.15.5-paddlenlp-latest .
      - name: Test CI Image
        run: |
          container_name=PaddleNLP-Build-test-${core_index}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker_image=iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu18.04-gcc8.2-cuda11.8-cudnn8.6-nccl2.15.5-paddlenlp-latest
          nvidia-docker run -d -t --name ${container_name} --net=host -v /dev/shm:/dev/shm --shm-size=32G \
          --runtime=nvidia ${docker_image} /bin/bash -c "
            python -c \"from paddlenlp import __version__; print('paddlenlp version:', __version__)\"
            python -c \"import paddlenlp; print('paddlenlp commit:', paddlenlp.version.commit)\"
            python -c \"import paddle; print('paddle'); print(paddle.__version__); print(paddle.version.show())\"
            python -m pip list
          "

      - name: Terminate And Delete the Container
        if: always()
        run: |
          docker rm -f ${{ env.container_name }}

  build-distribute-ci-docker:
    name: build-distribute-ci-docker
    runs-on: [self-hosted, distribute-v100]
    steps:
      - name: Download Code
        env:
          work_dir: ${{ github.workspace }}
        run: |
          sudo rm -rf * .[^.]*
          echo "Downloading PaddleNLP.tar.gz"
          wget -q --no-proxy  https://paddle-qa.bj.bcebos.com/CodeSync/develop/PaddleNLP.tar --no-check-certificate
          echo "Extracting PaddleNLP.tar.gz"
          tar xf PaddleNLP.tar && rm -rf PaddleNLP.tar
          source ${{ github.workspace }}/../../../proxy
          cd PaddleNLP
          git config --global user.name "PaddleCI"
          git config --global user.email "paddle_ci@example.com"
          git pull
          git submodule update --init --recursive --force
          git fetch origin pull/${PR_ID}/head
          git checkout -b PR_${PR_ID} FETCH_HEAD
          git remote add upstream https://github.com/PaddlePaddle/PaddleNLP.git
          git fetch upstream ${BRANCH}
          git merge ${BRANCH}
          git diff --numstat ${BRANCH} |awk '{print $NF}'
          git log --pretty=oneline -10

      - name: Write Dockerfile Inline
        env:
          work_dir: ${{ github.workspace }}/PaddleNLP
        run: |
          cat <<EOF > Dockerfile
          FROM registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda11.8-cudnn8.6-trt8.5-gcc82
          RUN unlink /usr/bin/python
          RUN ln -sf $(which python3.10) /usr/bin/python
          RUN python -m pip config --user set global.index http://pip.baidu-int.com/search/
          RUN python -m pip config --user set global.index-url http://pip.baidu-int.com/simple
          RUN python -m pip config --user set global.trusted-host pip.baidu-int.com
          RUN python -m pip install bce-python-sdk==0.8.74
          RUN python -m pip install --no-cache-dir https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuSome-LinuxCentos-Gcc82-Cuda118-Cudnn86-Trt85-Py310-CINN-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl
          COPY PaddleNLP/ /tmp/paddlenlp/
          WORKDIR /tmp/paddlenlp
          RUN python -m pip install -r requirements.txt
          RUN python -m pip install -r requirements-dev.txt
          RUN python -m pip install -r slm/model_zoo/gpt-3/requirements.txt
          RUN python setup.py bdist_wheel > /dev/null
          RUN python -m pip install dist/*.whl
          WORKDIR /
          RUN rm -rf /tmp/paddlenlp
          CMD ["python3"]
          EOF
      
      - name: Build Docker Image
        run: |
          docker build -t registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda11.8-cudnn8.6-trt8.5-gcc82-latest .

      - name: Test CI Image
        run: |
          container_name=PaddleNLP-distribute-Build-test-${core_index}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker_image=registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda11.8-cudnn8.6-trt8.5-gcc82-latest
          nvidia-docker run -d -t --name ${container_name} --net=host -v /dev/shm:/dev/shm --shm-size=32G \
          --runtime=nvidia ${docker_image} /bin/bash -c "
            python -c \"from paddlenlp import __version__; print('paddlenlp version:', __version__)\"
            python -c \"import paddlenlp; print('paddlenlp commit:', paddlenlp.version.commit)\"
            python -c \"import paddle; print('paddle'); print(paddle.__version__); print(paddle.version.show())\"
            python -m pip list
          "
      
      - name: Terminate And Delete the Container
        if: always()
        run: |
          docker rm -f ${{ env.container_name }}
