name: Lint

on: [push, pull_request]

jobs:
  Env:
    name: Install Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r ppdiffusers/requirements.txt
          pre-commit install

  Lint:
    name: Lint the package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run the project basic tools
        run: pre-commit run 

      - name: run isort
        run: make lint-isort

      - name: Is A Publish Branch
        if: steps.check-branch.outputs.match == 'true' && steps.should-deploy.outputs.should_deploy == 'true'
        env:
          TWINE_USERNAME: paddle-dev
          TWINE_PASSWORD: ${{ secrets.paddlenlp }}
        run: |
          make deploy-ppdiffusers

      - name: Should Not Deploy To Pypi Server
        if: steps.should-deploy.outputs.should_deploy != 'true'
        run: echo 'should not deploy pypi server'

      - name: Is Not A Publish Branch
        if: steps.check-branch.outputs.match != 'true'
        run: echo 'Not A Publish Branch'
