name: Lint

on: [push, pull_request]

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: checkout develop
        run: |
          git fetch origin develop
          git branch develop --track origin/develop
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install
      - name: run the command
        run: make lint
    
