name: PyPI

on: 
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to be Deploied'
        required: true
        default: 'paddlenlp'
        type: choice
        options:
        - paddlenlp
        - paddle-pipelines
        - ppdiffusers
        
  push:
    branches: 
      - 'develop'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install

  paddlenlp:
    name: Pack
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          make install

      - name: Set Default should_deploy Step Value
        id: default-should-deploy
        run:  echo "should_deploy='false'" >> $GITHUB_OUTPUT

      - name: Should Deploy to Pypi Server
        id: should-deploy
        if: ${{ inputs.package == 'paddlenlp' }}
        run: python scripts/should_deploy.py  --name paddlenlp >> $GITHUB_OUTPUT
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.ref }} =~ ^refs/heads/(develop)$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi  # See: https://stackoverflow.com/a/58869470/1123955

      - name: Is A Publish Branch
        if: steps.check-branch.outputs.match == 'true' && steps.should-deploy.outputs.should_deploy == 'true'
        env:
          TWINE_USERNAME: paddle-dev
          TWINE_PASSWORD: ${{ secrets.paddlenlp }}
        run: |
          make deploy-paddlenlp

      - name: Should Not Deploy To Pypi Server
        if: steps.should-deploy.outputs.should_deploy != 'true'
        run: echo 'should not deploy pypi server'

      - name: Is Not A Publish Branch
        if: steps.check-branch.outputs.match != 'true'
        run: echo 'Not A Publish Branch'

  ppdiffusers:
    name: Pack
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          make install-ppdiffusers

      - name: Should Deploy to Pypi Server
        id: should-deploy
        run: python scripts/should_deploy.py  --name ppdiffusers >> $GITHUB_OUTPUT
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.ref }} =~ ^refs/heads/(develop)$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi  # See: https://stackoverflow.com/a/58869470/1123955

      - name: Is A Publish Branch
        if: steps.check-branch.outputs.match == 'true' && steps.should-deploy.outputs.should_deploy == 'true'
        env:
          TWINE_USERNAME: paddle-dev
          TWINE_PASSWORD: ${{ secrets.paddlenlp }}
        run: |
          make deploy-ppdiffusers

      - name: Should Not Deploy To Pypi Server
        if: steps.should-deploy.outputs.should_deploy != 'true'
        run: echo 'should not deploy pypi server'

      - name: Is Not A Publish Branch
        if: steps.check-branch.outputs.match != 'true'
        run: echo 'Not A Publish Branch'

  paddle_pipelines:
    name: Pack
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          make install-paddle-pipelines

      - name: Should Deploy to Pypi Server
        id: should-deploy
        run: python scripts/should_deploy.py  --name paddle-pipelines >> $GITHUB_OUTPUT
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.ref }} =~ ^refs/heads/(develop)$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi  # See: https://stackoverflow.com/a/58869470/1123955

      - name: Is A Publish Branch
        if: steps.check-branch.outputs.match == 'true' && steps.should-deploy.outputs.should_deploy == 'true'
        env:
          TWINE_USERNAME: paddle-dev
          TWINE_PASSWORD: ${{ secrets.paddlenlp }}
        run: |
          make deploy-paddle-pipelines

      - name: Should Not Deploy To Pypi Server
        if: steps.should-deploy.outputs.should_deploy != 'true'
        run: echo 'should not deploy pypi server'

      - name: Is Not A Publish Branch
        if: steps.check-branch.outputs.match != 'true'
        run: echo 'Not A Publish Branch'
