name: Re-run

on:
  issue_comment:
    types: [created]

jobs:
  re-run:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/re-run')  && github.event.comment.user.login == github.event.issue.user.login }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rerun all failed jobs
        if: ${{ contains(github.event.comment.body, 'all-failed') }}
        uses: ./.github/actions/rerun-workflow
        with:
          PR_ID: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          JOB_NAME: 'all-failed'

      - name: Rerun LLM
        if: ${{ contains(github.event.comment.body, 'LLM') }}
        uses: ./.github/actions/rerun-workflow
        with:
          PR_ID: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          JOB_NAME: 'PaddleNLP LLM CI / llm-test'

      - name: Rerun Unit GPU
        if: ${{ contains(github.event.comment.body, 'Unit GPU') }}
        uses: ./.github/actions/rerun-workflow
        with:
          PR_ID: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          JOB_NAME: 'PaddleNLP Unit GPU CI / unit-gpu-test'
        
      - name: Rerun Unit CPU
        if: ${{ contains(github.event.comment.body, 'Unit CPU') }}
        uses: ./.github/actions/rerun-workflow
        with:
          PR_ID: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          JOB_NAME: 'PaddleNLP Unit CPU CI / unit-cpu-test'

      - name: Rerun Distribute
        if: ${{ contains(github.event.comment.body, 'Distribute') }}
        uses: ./.github/actions/rerun-workflow
        with:
          PR_ID: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          JOB_NAME: 'PaddleNLP Distribute CI / distribute-test'
